name: cicd
on: [push, workflow_dispatch]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: publish packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for pom in repository/*.pom; do \
          mvn -f $pom org.honton.chas:exists-maven-plugin:0.8.0:remote -Dexists.serverId=github -Dexists.repository=https://maven.pkg.github.com/metasfresh/metasfresh-maven-repo -DfailIfNotExists=true \
          && echo "* $pom: already present" >> $GITHUB_STEP_SUMMARY \
          || mvn deploy:deploy-file -Durl=https://maven.pkg.github.com/metasfresh/metasfresh-maven-repo -DrepositoryId=github -Dfile="${pom%%.pom}.jar" -DgeneratePom=false -DpomFile="$pom" \
          && echo "* $pom: deployed" >> $GITHUB_STEP_SUMMARY
          ; done